---
config:
  look: neo
---
classDiagram
direction TB
    class LoadData {
	    +load_data(file_path)
	    +export_dataframes_to_csv()
    }
    class MainOrchestrator {
	    +model_name: String
	    +model_name_finetuned:String
	    +invokeZeroShotPipeline()
	    +invokeFewShotPipeline()
	    +invokeFineTunedPipeline()
    }
    class ZeroShotPipeline {
	    +processReviewsWithZeroShot()
	    +runSynChainZeroShot()
    }
    class FewShotPipeline {
	    +processReviewsWithFewShot()
	    +runSynChainFewShot()
    }
    class FineTunedGPTPipeline {
	    +processReviewsWithFineTuned()
	    +runFineTuned()
    }
    class PromptTemplates {
	    +SYSTEM_PROMPT_ASPECT
	    +SYSTEM_PROMPT_POLARITY
	    +SYSTEM_PROMPT_FINETUNED
	    +USER_TEMPLATE_ASPECT
	    +USER_TEMPLATE_POLARITY
    }
    class EvaluateResults {
	    -parse_label()
	    +collect()
	    +evaluate()
	    +save()
    }
    class PerformanceTracker {
	    -results_dir: String
	    -file: String
	    -performance_data:Dict
	    +load_data()
	    +addRun()
	    +update()
	    +save()
	    +printSummary()
	    +get_comparison_report()
    }
    class OpenAIAPIClient {
	    -client:OpenAI
	    +request(model, review, systemPrompt)
    }
    class ZeroShotResults {
	    +review_id: int
	    +review_body: String
	    +true_labels: list
	    +predicted_labels: list
	    +extracted_aspects: list
	    +justification: String
    }
    class FewShotResults {
	    +review_id: int
	    +review_body: String
	    +true_labels: list
	    +predicted_labels: list
	    +extracted_aspects: list
	    +justification: String
    }
    class FineTunedResults {
	    +review_id: int
	    +review_body: String
	    +true_labels: list
	    +predicted_labels: list
	    +extracted_aspects: list
	    +justification: String
    }

	<<Data>> ZeroShotResults
	<<Data>> FewShotResults
	<<Data>> FineTunedResults

    LoadData --> MainOrchestrator
    MainOrchestrator o--> ZeroShotPipeline
    MainOrchestrator o--> FewShotPipeline
    MainOrchestrator o--> FineTunedGPTPipeline
    ZeroShotPipeline ..|> OpenAIAPIClient
    FewShotPipeline ..|> OpenAIAPIClient
    FineTunedGPTPipeline ..|> OpenAIAPIClient
    OpenAIAPIClient --> PromptTemplates
    ZeroShotPipeline --> ZeroShotResults
    FewShotPipeline --> FewShotResults
    FineTunedGPTPipeline --> FineTunedResults
    ZeroShotResults --> EvaluateResults
    FewShotResults --> EvaluateResults
    FineTunedResults --> EvaluateResults
    MainOrchestrator --> PerformanceTracker
    PerformanceTracker <-- EvaluateResults
