[project]
name = "dw082-ba-ss25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=3.5.0",
    "openai>=1.76.2",
    "pandas>=2.2.3",
    "python-dotenv>=1.1.0",
    "scikit-learn>=1.6.1",
    "spacy>=3.8.5",
    "torch>=2.6.0",
    "transformers>=4.50.1",
]
